### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by cuge1995** [AutoVision-cloud/Deformable-PV-RCNN#5]
* The deformation module
```python
if src_name in self.model_cfg.DEF_SOURCE:
```

```shell
DEF_SOURCE: ['x_conv1', 'x_conv2', 'x_conv3', 'x_conv4']
```
It seems that you used four defomation mudule in code, but only show  'x_conv3' and  'x_conv4' in paper.

* The context fusion module

It seems that the context fusion module is inside the `StackSAModuleMSGAdapt`, but it shown that this module is outside pointnet++ module in paper.

looking forward to your reply,
Jinlai Zhang

**Comment by AutoVision-cloud** [comment]
Hi, 
Yes we have used only `conv3` and `conv4` in the paper, since these are the layers with more semantically meaningful features for deformation. But in the results section of this repository, we release both - models with all convolutional feature combined, and one with only `conv3` and `conv4`. 
The Context Fusion module is in the `StackSAModuleMSGGated()`.
